### ISSUE TITLE
error 500

### ISSUE THREAD

**Issue by brasizza** [nfephp-org/sped-nfse-prodam#12]
** Nota: para questões de suporte, use Google Groups https://groups.google.com/forum/#!forum/nfephp **. Os problemas deste repositório são reservados para solicitações de recursos e relatórios de erros.

* **Estou enviando um ...**
  - [x] bug
  - [ ] requisição de funcionalidade
  - [ ] requisição de suporte => Por favor, não envie solicitação de suporte aqui, veja a nota no topo deste modelo.

Estou tentando fazer uma requisição mas esta dando error 500

  protected 'message' => string 'An error occurred while trying to communication via soap,   [https://nfews.prefeitura.sp.gov.br/lotenfeasync.asmx] HTTP Error code: 500 - ' (length=138)

**Comment by robmachado** [comment]
Erro 500 é um erro no servidor da Prefeitura

**Comment by vpereirasoma** [comment]
Caso semelhante aqui comigo..
Fatal error:  Uncaught NFePHP\Common\Exception\SoapException: An error occurred while trying to communication via soap,   [https://nfews.prefeitura.sp.gov.br/lotenfeasync.asmx] HTTP Error code: 500 -  in /var/www/html/somanfe/vendor/nfephp-org/sped-common/src/Exception/SoapException.php:24
Stack trace:
#0 /var/www/html/somanfe/vendor/nfephp-org/sped-nfse-prodam/src/Common/Soap/SoapCurl.php(111): NFePHP\Common\Exception\SoapException::soapFault(' [https://nfews...')
#1 /var/www/html/somanfe/vendor/nfephp-org/sped-nfse-prodam/src/Common/Tools.php(158): NFePHP\NFSeProdam\Common\Soap\SoapCurl->send('EnvioLoteRpsAsy...', 'https://nfews.p...', 'http://www.pref...', '<?xml version="...', Array)
#2 /var/www/html/somanfe/vendor/nfephp-org/sped-nfse-prodam/src/Tools.php(362): NFePHP\NFSeProdam\Common\Tools->send('<PedidoEnvioLot...', 'EnvioLoteRpsAsy...', 'assincrono')
#3 /var/www/html/somanfe/app/control/nfse/prodam/NFSeProdamHandle.php(97): NFePHP\NFSeProdam\Tools->recepcionarLoteRps(Array, false)
#4 /var/www/html/somanfe/app/cont in /var/www/html/somanfe/vendor/nfephp-org/sped-common/src/Exception/SoapException.php on line 24
